FROM bde2020/hadoop-namenode:2.0.0-hadoop3.3.6

USER root

# Install additional dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER root
